id: I3AE738A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T09:37:42+00:00'
last_modified: '2022-06-13T12:48:22.443072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD1002
  title: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E98E:
      image_group_id: I1KG81113
      title: ''
      total_pages: ''
      order: 1
      base_file: E98E.txt
    0E6F:
      image_group_id: I1KG81114
      title: ''
      total_pages: ''
      order: 2
      base_file: 0E6F.txt
    E920:
      image_group_id: I1KG81115
      title: ''
      total_pages: ''
      order: 3
      base_file: E920.txt
    '0606':
      image_group_id: I1KG81116
      title: ''
      total_pages: ''
      order: 4
      base_file: 0606.txt
    F881:
      image_group_id: I1KG81117
      title: ''
      total_pages: ''
      order: 5
      base_file: F881.txt
    34CD:
      image_group_id: I1KG81118
      title: ''
      total_pages: ''
      order: 6
      base_file: 34CD.txt
    '0447':
      image_group_id: I1KG81119
      title: ''
      total_pages: ''
      order: 7
      base_file: 0447.txt
    7F92:
      image_group_id: I1KG81120
      title: ''
      total_pages: ''
      order: 8
      base_file: 7F92.txt
    990C:
      image_group_id: I1KG81121
      title: ''
      total_pages: ''
      order: 9
      base_file: 990C.txt
    A7FA:
      image_group_id: I1KG81136
      title: ''
      total_pages: ''
      order: 24
      base_file: A7FA.txt
    010C:
      image_group_id: I1KG81123
      title: ''
      total_pages: ''
      order: 11
      base_file: 010C.txt
    '5609':
      image_group_id: I1KG81124
      title: ''
      total_pages: ''
      order: 12
      base_file: 5609.txt
    '9204':
      image_group_id: I1KG81125
      title: ''
      total_pages: ''
      order: 13
      base_file: 9204.txt
    243B:
      image_group_id: I1KG81126
      title: ''
      total_pages: ''
      order: 14
      base_file: 243B.txt
    777C:
      image_group_id: I1KG81127
      title: ''
      total_pages: ''
      order: 15
      base_file: 777C.txt
    0F96:
      image_group_id: I1KG81128
      title: ''
      total_pages: ''
      order: 16
      base_file: 0F96.txt
    9CC6:
      image_group_id: I1KG81129
      title: ''
      total_pages: ''
      order: 17
      base_file: 9CC6.txt
    B141:
      image_group_id: I1KG81130
      title: ''
      total_pages: ''
      order: 18
      base_file: B141.txt
    4B80:
      image_group_id: I1KG81131
      title: ''
      total_pages: ''
      order: 19
      base_file: 4B80.txt
    4C4D:
      image_group_id: I1KG81132
      title: ''
      total_pages: ''
      order: 20
      base_file: 4C4D.txt
    A884:
      image_group_id: I1KG81133
      title: ''
      total_pages: ''
      order: 21
      base_file: A884.txt
    '2360':
      image_group_id: I1KG81134
      title: ''
      total_pages: ''
      order: 22
      base_file: 2360.txt
    B551:
      image_group_id: I1KG81135
      title: ''
      total_pages: ''
      order: 23
      base_file: B551.txt
    EF6B:
      image_group_id: I1KG81137
      title: ''
      total_pages: ''
      order: 25
      base_file: EF6B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
